# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YeahMin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'LGSideMenuController'


  # Pods for YeahMin

  target 'YeahMinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
